frameworkVersion: ^3.16.0

service: feel-the-bot

provider:
  name: aws
  profile: default
  runtime: nodejs14.x
  environment:
    APP_ID: 171773
    PRIVATE_KEY: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEA7v/2bW6ckTCMkxEWOIYx3hHsLxO7/yaEAdPoeEu9n5NxXMUW
      ktOvZTTUOkz+WY/KlRnF2RK/8l4UREL2ogahGnkjPzfLjK2tRtybQJn6cKyQYZrC
      J70hxgeqPGtVPqQcL0TXHs/lbl6YVLiTXoju74zK7qY4ESW6t7q3+zJTdICwbcyR
      LQYyAcTl8vgqLQQMtxZpP++yxzDkLn2lDoo1USTBcS3lxSlEXuJwMaBeA6J3o08c
      lBXCd875GBLh36Ing9sD9CaWCcFmrMHRXcOIz764UAZjRJY+Qdlc02RTeiq0f3EJ
      9YEF1Im8we/OHQMqNp9G2C7AQw7lSDggn5WqKwIDAQABAoIBAQCkr3235FtAdIq5
      IDIGmvmrwv/TZK7LX1fhBosOsWollmyr9ybZ38HhZCjFT56ISlvWp967+H6JXKhs
      bRQTi6vhWQ2flyvMcTSQOp1EQ5XdpBsNFp2o0lt+YHO+lFs2AdFmBPKSycCXb9lZ
      r6Hkp0i1inefQKwrrKrfxWrXTdNR17I742WHOcz7ibLkoIYpiB/FuPir5uorbzH6
      LKNQBa8ArufR2VHRs1JTyhNkmC7q6+xzJRZGpl9sPnFtLPwurskEf7qzzKg8bpfF
      76hkWBNrZDrvzoxO8XWs8Q/AxKHz3zZXNNMQsF9+v74dPX9DbuDTaGWA+XqAYhP/
      ZFtdZXo5AoGBAP2dYU+EVH21ZGv4BacSvxUpbPbyyEcmhckMUqkmpGR54oHM7QH3
      fcG2J8d+LMAAgOw1lkXwbyhN3q1mjEe5w4XxiTkmJd3PE0loIuEat4JMdwjgXSf7
      mPDnj3R/l9YLDAfq+/S9ttutiEAj1iQU96DzWtamwua0H9biIgHQwH8XAoGBAPE/
      ZQebN6iCyF91oWFvWJRcTIanPu83g8Act3YTzZTOOR/i1MrSFFyHnAAyLm574mFO
      /9sC7eYmwOZ0maioCzldb6eUwbLgl3L2EKX3QG4Bq1G9tnwWtrLc2BE2TTEQ5ZOB
      EaTV5y1FAQorSQ8EUd+4+tzVqk0LjI7DAiIhnDoNAoGBAJwnauMq91rvdQWFkPVt
      9XlyKEVk9yvX7Ef97md4A4BaC70gEE5FtIixP4z1g1g09yx5Ui19/PMz/weFPJpt
      JpYyQeuOMYKBHb70/4TajmML8b7lZnZX07OA4DM63KJN6vp1FO18YjqgfmP/rLpK
      rq3LKQNBan/iKDiGw6mafuvBAoGAAcJynDGXoFUD3R5ghPNo8/wQWtMRdHE1Nst+
      0w+l6jXu2LqwzqHloB8lFiNHj2q75fXLi+9jiNAzi/rBvCctncd+rvw4xXM5546/
      5FX/VE4Sz8/QautHfdp6gPWibn8vDXpdhJRC0WO1dDuIluFzL2yL99xfF5zD866c
      b19LYmkCgYEA5jorr/8BZfqCo3FM/10GtX0cd3dfVUPt2LT5qLhTX2jlrr2Ukv2n
      Y8A3UEnYEBw4ja62yTcEuGGH7OA4c3yDPZ+O9+NP4neaUhCz83mOfVlMWPOwSKig
      QNHE/hbRwv71CEpKsUuZcwe2+yl83FSQoJiHjt+uFvpjVhSTcWbw1LM=
      -----END RSA PRIVATE KEY-----
    WEBHOOK_SECRET: e871f75323907c6bc7c9ca12051e401573198b54
    GITHUB_CLIENT_ID: Iv1.f74aef20577b3206
    GITHUB_CLIENT_SECRET: d1635fc1303f70ee63f9c3449096962b32cd84b0
    GITHUB_TOKEN: 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
    GREENHOUSE_API_KEY: b2d6dd73416c64bc6e8971b23b7ced8979722c5e5929e92ae9a4c5b9ca85ab72
    NODE_ENV: production
    LOG_LEVEL: debug

functions:
  http:
    handler: handler.http
    events:
      - httpApi: '*'