name: 'End coding challenge'

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'GitHub user'
        required: true
      repo:
        description: 'GitHub repository'
        required: true

jobs:
  end-challenge:
    name: 'End challenge'
    runs-on: ubuntu-latest
    steps:

    - uses: actions/github-script@v5
      id: revoke-access-to-repo
      with:
        github-token: ${{ secrets.PAT }}
        script: |
          const user = "${{ github.event.inputs.user }}"
          const repo = "${{ github.event.inputs.repo }}"
        
          return await github.rest.repos.removeCollaborator({
            owner: context.repo.owner,
            repo: repo,
            username: user,
          })
