name: 'End interview'

on:
  workflow_dispatch:
    inputs:
      github_user:
        description: 'GitHub user'
        required: true
      github_repo:
        description: 'GitHub repository'
        required: true

jobs:
  end-interview:
    name: 'End interview'
    runs-on: ubuntu-latest
    steps:

    - uses: actions/github-script@v5
      id: create-repo
      with:
        github-token: ${{ secrets.PAT }}
        script: |
          const user = "${{ github.event.inputs.github_user }}"
          const repo = "${{ github.event.inputs.github_repo }}"
        
          return await github.rest.repos.removeCollaborator({
            owner: context.repo.owner,
            repo: repo,
            username: user,
          })
