name: "Test"

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  units:
    name: 'Unit test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: | 
        npm ci
        npm test
      working-directory: ./action

  # test action works running from the graph
  test:
    name: 'Run wait'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./action
      with:
        milliseconds: 1000